# Generated by Django 5.0.1 on 2024-01-07 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='nutrients',
            new_name='ingridient_batch',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='ingridient',
        ),
    ]
